// Geolacalizacón
const URL_PROVINCES = "https://apis.datos.gob.ar/georef/api/provincias";

const URL_MUNICIPALITIES = "https://apis.datos.gob.ar/georef/api/municipios";

const PAGESIZE = 10

const STATE_VIEW = 'view'
const STATE_PENDING = 'pending'
const STATE_ACCEPTED = 'accepted'
const STATE_CANCELLED = 'cancelled'
const STATE_RATINGPENDING = 'ratingPending'
const STATE_RATINGCUSTOMERPENDING = 'ratingCustomerPending'
const STATE_RATINGPROVIDERPENDING = 'ratingProviderPending'
const STATE_COMPLETED = 'completed'

const USER_ADMINISTRATOR='administrator'
const USER_CUSTOMER='customer'
const USER_PROVIDER='provider'
const USER_EXTERNAL='external'

const PEOPLE_STATE_ACTIVE='Active'
const PEOPLE_STATE_INACTIVE='Inactive'
const PEOPLE_STATE_DELETED='Deleted'
const PEOPLE_STATE_FIRST_PAYMENT_PENDING='First Payment Pending'
const PEOPLE_STATE_PENDING_DEBT='Pending Debt'

const TYPE_OF_QUESTION_FAQ='faq'
const TYPE_OF_QUESTION_QAA='qaa'

module.exports = {
    URL_PROVINCES, URL_MUNICIPALITIES, PAGESIZE,
    STATE_ACCEPTED, STATE_CANCELLED, STATE_COMPLETED, STATE_PENDING,
    STATE_RATINGCUSTOMERPENDING, STATE_RATINGPENDING,
    STATE_RATINGPROVIDERPENDING, STATE_VIEW,
    USER_ADMINISTRATOR,USER_CUSTOMER,USER_PROVIDER,USER_EXTERNAL,
    PEOPLE_STATE_ACTIVE,PEOPLE_STATE_DELETED,PEOPLE_STATE_INACTIVE,PEOPLE_STATE_FIRST_PAYMENT_PENDING,PEOPLE_STATE_PENDING_DEBT,
    TYPE_OF_QUESTION_FAQ,TYPE_OF_QUESTION_QAA};